name: Backend API CI
on:
  push:
    paths:
      - 'api/**'
  pull_request:
    paths:
      - 'api/**'

jobs:
  build-backend:
    name: Build API
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          distribution: 'corretto'
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant Permission to Execute
        run: chmod +x gradlew
        working-directory: api

      - name: Build with Gradle
        run: ./gradlew build --stacktrace
        working-directory: api